//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eszkozok
    {
        public int Sorszam { get; set; }
        public string Leltari_szam { get; set; }
        public string Tipus { get; set; }
        public string MAC { get; set; }
        public int Besz_eve { get; set; }
        public string Gyarto { get; set; }
    }
}
